# Site settings

title: Research Blog
header-img: img/home-bg.jpg
email: latmarat@gmail.com
description: "MINED Multiscale Materials Modeling Group"
baseurl: "/group-blog"
url: "http://mined-simulations.github.io"
github_username:  mined-simulations
project_repository: group-blog

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
